name: Create PR

on:
  push:
    branches:
      - master

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: date +%s > report.txt

      - uses: proudust/create-pull-request@using-ssh
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deploy-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
